pipeline:
  build:
    image: jwmarshall/drone-make
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - make all

  publish:
    image: jwmarshall/drone-make
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - export
      - docker login --username "${DOCKER_USERNAME}" --password "${DOCKER_PASSWORD}"
      - make all PUSH=true
