pipeline:
  build:
    image: jwmarshall/drone-make
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - make all
  push:
    image: jwmarshall/drone-make
    volumes:
      - /var/run/docker.dock:/var/run/docker.sock
    commands:
      - make all PUSH=true
