pipeline:
  build:
    image: jwmarshall/drone-make
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - make all

  push:
    image: jwmarshall/drone-make
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - export
      - docker login --username "${docker_username}" --password "${docker_password}"
      - make all PUSH=true
