pipeline:
  build:
    image: jwmarshall/drone-make
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - make all

  push:
    image: jwmarshall/drone-make
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - export
      - docker login
      - make all PUSH=true
